### ISSUE TITLE
aarch64 compatability

### ISSUE THREAD

**Issue by resistor4u** [kazcw/jh-x86_64#1]
would changing "x86_64" to "aarch64" or "arm64" in e.g. [this declaration](https://github.com/kazcw/jh-x86_64/blob/ff272103ab6230435f55d91de86bc1cff4a4e6b2/src/lib.rs#L6) and elsewhere prompt a successful aarch64 build, or would compiling on aarch64 linux require a total rewrite?

ideally, i'd like to build kazcw/powhasher#1 on an RPi 3b+ running a 64-bit (not 32-bit) OS. those build attempts fail at groestl-aesni, which in turn point here.

**Comment by kazcw** [comment]
This crate, [kazcw/groestl-aesni](https://github.com/kazcw/groestl-aesni), and [kazcw/yellowsun](https://github.com/kazcw/yellowsun) (the core CryptoNight implementation) are all optimized/hardware-accelerated for x86-64 and would need to be completely rewritten or replaced.

Also, the RPi 3b+ doesn't have the NEON extensions for hardware AES, so it would need a slow software implementation. You'd be much better off with something that's ARMv8-A like the Pine64, which wouldn't crank out a lot of hashes but might be power-efficient.

**Comment by kazcw** [comment]
So, I'm closing this as not-currently-in-scope because it requires significant work (or a lot of copy-pasting from other implementations, but then what's the point?) and I don't have the hardware to run it on.
